version: '3.8'
services:
  web:
    image: python:3.11-slim
    container_name: flask_web
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
      pip install --no-cache-dir -r requirements.txt &&
      gunicorn --bind 0.0.0.0:8000 app:app
      "
  nginx:
    image: nginx:stable-alpine
    container_name: flask_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
